### ISSUE TITLE
Add filtering/searching by the Event field

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#140]
All looks like I can filter alerts on the alerts page only by the `Resource` and `Description` columns. The same is true for searching alerts in the `Search` box.

Is it possible to add filtering/searching by the `Event` field?

**Comment by satterly** [comment]
<img width="674" alt="Screenshot 2019-04-12 at 13 44 59" src="https://user-images.githubusercontent.com/615057/56034969-2eb27380-5d29-11e9-83e1-6b6d70864550.png">

**Comment by vykulakov** [comment]
Fine, thanks.

Could you add the same functionality to the filter?

**Comment by satterly** [comment]
No, sorry. There are lots of alert attributes and `event` is just one -- where do I stop? I've added what I think are the most useful. If you believe `event` should be added let me know which one should be removed :)

**Comment by vykulakov** [comment]
It is quite strange for me: why I can type `event:TestAlert` in the Search box and can not do the same thing in the Search field of the filter.

**Comment by satterly** [comment]
Oh, I see what you mean. You can type "total processes" in that search box and it will find the alert...
<img width="935" alt="Screenshot 2019-04-12 at 14 07 06" src="https://user-images.githubusercontent.com/615057/56036109-522aed80-5d2c-11e9-9c3a-3b7f4e6d512d.png">
Note that it needs to be in lowercase. I think that is the confusing part. I will change it so that it's not case-sensitive.

**Comment by vykulakov** [comment]
Yes, I see that it works now... But only when we search text is in lowercase. :) Thanks for the fast fix.
